### PR TITLE
Added url to python implementation

### PR DESCRIPTION
**Pull request by djetelina**
Hopefully this isn't too shameless :) - Once it's more idiomatic, I'll gladly pull request the implementation standalone into here.

### CODE REVIEW

**Comment by djetelina** [comment]
Any thoughts on this? Perhaps a suggestion for *modify*cation of the PR?

**Comment by nunesvictor** [comment]
Maybe you can fork the repo and add your implementation to it... I think it will be better to keep all the implementations is the same place.

**Comment by nunesvictor** [comment]
I was gonna say I was about to do so, but I saw your PR and think maybe you have some priority on it.

**Comment by djetelina** [comment]
@nunesvictor To be frank, I'd love for my library to be the recommended wait of using this and all future APIs in Python. 
In my mind it makes more sense to have an opensource updated library that everyone uses than an implementation without tests and means of distribution in this repository that's copied to every project. 
But - I know it's unlikely for Valve to endorse my library without at least establishing trust first - so I don't mind adjusting the implementation and posting it in full into a python directory in this repo - but I'd love to hear from somebody at Valve first, seeing as #10 isn't getting merged either.

**Pull request closed without merging**
